// ─────────────────────────────────────────────────────────────────────────────
//  FANTASKY MASTER · LEAGUE DATA
//  This is the only file you need to edit to keep the league up to date.
//
//  After an episode airs:
//    1. Append its tasks to that series' `tasks` (scores `s` in `cast` order,
//       which is the show's seating order: alphabetical by first name).
//       Adding tasks for an episode is what marks it as "scored".
//    2. Add each player's final poll vote to `picks` (array index 0 = Episode 1;
//       use null for a missed poll). Future picks can go in early; they only
//       count once their episode is scored.
//    3. Only if contestants tied for the top score: add `tb: "Name"` (the
//       tiebreak winner) to that episode in `episodes`.
//
//  Task types: P = prize, F = filmed, T = team, L = live (studio).
//  Air dates are London dates; every episode goes live at 22:00 London time.
//  Task scores sourced from the Taskmaster Wiki (taskmaster.fandom.com).
// ─────────────────────────────────────────────────────────────────────────────

const img = (id) => `https://i.imgur.com/${id}m.webp`;

export const SERIES = {
  22: {
    theme: "greek",
    themeName: "Ancient Greek",
    location: "London Museum of Water & Steam",
    album: "https://imgur.com/a/taskmaster-series-22-r7FwUp3",
    teams: [["Chloe", "Matt", "Richard"], ["Isy", "Nina"]],
    champion: null,
    cast: [
      { key: "Chloe", full: "Chloe Petts", color: "#d0643f", img: img("8ZFXOSZ"),
        bio: "Critically acclaimed stand-up and an Edinburgh Fringe favourite." },
      { key: "Isy", full: "Isy Suttie", color: "#3f86c4", img: img("Mqxwewi"),
        bio: "Comedian, writer, songwriter and actor, best known as Dobby in Peep Show." },
      { key: "Matt", full: "Matt Lucas", color: "#8fa23b", img: img("A4Eabuj"),
        bio: "BAFTA-winning co-creator of Little Britain, former Bake Off host, and Nardole in Doctor Who." },
      { key: "Nina", full: "Nina Conti", color: "#9a62c2", img: img("Tf5CoeT"),
        bio: "Ventriloquist, comedian and actor, rarely seen without a foul-mouthed monkey." },
      { key: "Richard", full: "Richard Ayoade", color: "#d9a62e", img: img("Az8PJmE"),
        bio: "Moss in The IT Crowd, director of Submarine, and host of Travel Man and The Crystal Maze." },
    ],
    episodes: [
      { ep: 1, title: "In My Mind There's a River", date: "2026-09-03" },
      { ep: 2, title: "This Is Food Glue", date: "2026-09-10", tb: "Richard",
        tbTask: "Guess the temperature of the liquid in the flask" },
      { ep: 3, title: "The Butterfly Centurion", date: "2026-09-17" },
      { ep: 4, title: "An Act of Self-Erasure", date: "2026-09-24" },
      { ep: 5, title: "You're Nice", date: "2026-10-01" },
      { ep: 6, title: "To Void an Oblong", date: "2026-10-08" },
      { ep: 7, title: "The Oldest I've Ever Looked", date: "2026-10-15" },
      { ep: 8, title: null, date: "2026-10-22" },
      { ep: 9, title: null, date: "2026-10-29" },
      { ep: 10, title: null, date: "2026-11-05" },
    ],
    tasks: [
  // Episode 1
  { ep: 1, t: "P", n: "Droopiest object", s: [2, 5, 3, 4, 1],
    d: "Droopiest object." },
  { ep: 1, t: "F", n: "Put the golden apple on the golden plate", s: [3, 0, 5, 4, 0],
    d: "Your first task is to put the golden apple on the golden plate. If the golden apple touches the ground, you are disqualified. Also, you must be handcuffed to Alex throughout." },
  { ep: 1, t: "T", n: "Move this bed into the living room", s: [5, 2, 5, 2, 5],
    d: "Move this bed into the living room. You may not look at each other and you may only say words with one syllable. For every stray glance, scuff mark or extra syllable, a minute will be added to your time." },
  { ep: 1, t: "F", n: "Perform a passionate duet with yourself about yourselves", s: [5, 4, 3, 5, 2],
    d: "Perform a passionate duet with yourself about yourselves. You must sing both parts." },
  { ep: 1, t: "L", n: "Hold up the item or items that the Taskmaster shouts", s: [4, 2, 1, 3, 5],
    d: "Hold up the item or items that the Taskmaster shouts. You may only look in your belts after the Taskmaster has shouted. You must not remove your belts at any point. Also, you must beep while searching. Slowest player each round is eliminated." },
  // Episode 2
  { ep: 2, t: "P", n: "Best thing you have been given that would not make the Taskmaster jealous", s: [4, 5, 3, 1, 2],
    d: "Best thing you have been given that would not make the Taskmaster jealous." },
  { ep: 2, t: "F", n: "Work out the height of the tower in baked beans", s: [2, 1, 3, 4, 5],
    d: "Work out the height of the tower in baked beans. You must smile throughout." },
  { ep: 2, t: "F", n: "Discover a face on a piece of toast", s: [1, 2, 5, 4, 3],
    d: "Discover a face on a piece of toast. You have one loaf of bread and you must not render more than three slices of bread inedible." },
  { ep: 2, t: "F", n: "Do either the buggy, bounce or beans task", s: [0, 0, 0, 5, 4],
    d: "Pick a three-digit number and then do either the buggy, bounce or beans task. Leave exactly your number of balls in the buggy. Bounce exactly your number of times. You must be airborne for your bounce to count. Eat exactly your number of baked beans." },
  { ep: 2, t: "L", n: "Get to the centre spot first", s: [1, 5, 3, 0, 0],
    d: "Get to the centre spot first. On the horn, hold up a paddle to indicate which contestant cannot progress. You may only move forward if your colour isn't chosen. You may converse between horns." },
  // Episode 3
  { ep: 3, t: "P", n: "The thing that makes them feel safest", s: [4, 1, 5, 2, 3],
    d: "The thing that makes them feel safest." },
  { ep: 3, t: "F", n: "Gleek", s: [3, 1, 2, 5, 4],
    d: "Gleek. You may not use the internet but you may make two phone calls as long as you only yell and the phone calls last no more than thirty seconds each." },
  { ep: 3, t: "F", n: "Take a pair of photos, one before and one after something happening", s: [6, 3, 1, 5, 3],
    d: "Take a pair of photos, one before and one after something happening. Bonus: most unexpected thing that happened in between the photos." },
  { ep: 3, t: "F", n: "Win a game of Noughts and Crosses against your old self", s: [3, 4, 2, 5, 1],
    d: "Win a game of Noughts and Crosses against your old self. Your old self will choose squares according to the form they filled in earlier. If you fail to land a nought in an empty square, you miss a go. If you win, you must give the same answer as your old self, and then your task is over. If you give a different answer, you must start again." },
  { ep: 3, t: "L", n: "Get all the loo rolls onto the correct pole", s: [5, 0, 3, 0, 0],
    d: "Get all the red rolls on your left pole, the yellow rolls on your middle pole and the green rolls on your right pole. Only one roll may leave the poles at any time. Also, you must be waving at the Taskmaster with one hand throughout the task." },
  // Episode 4
  { ep: 4, t: "P", n: "Juiciest thing", s: [3, 5, 3, 4, 2],
    d: "Juiciest thing." },
  { ep: 4, t: "F", n: "Say your seven times table", s: [2, 5, 3, 4, 1],
    d: "Find and complete the actual task. Everything you say from now on must be a question. If you say something that isn't a question, one minute will be added to your time, will it? Now look under the table? Say your seven times table." },
  { ep: 4, t: "T", n: "Create the most powerful piece of art involving one or more of your armpits", s: [4, 5, 4, 5, 4],
    d: "Create the most powerful piece of art involving one or more of your armpits." },
  { ep: 4, t: "F", n: "Convince everyone you are wearing the official workplace earpiece", s: [5, 5, 0, 5, 0],
    d: "Convince everyone you are wearing the official workplace earpiece, or if you are wearing the official workplace earpiece, convince everyone that you are not. If you are wearing the official workplace earpiece, you must obey all five instructions. If the Taskmaster fails to identify the worker, the worker gets five points. If a fellow contestant mistakenly accuses someone else of being the worker, that person gets five points. Nobody else gets any points." },
  { ep: 4, t: "L", n: "Draw the picture described by the Taskmaster while making eye contact with the Taskmaster", s: [5, 4, 2, 3, 2],
    d: "Draw the picture described by the Taskmaster while making eye contact with the Taskmaster. You can only look at your picture while the Taskmaster is shouting \"Bayeux Tapestry\"." },
    ],
    // Final poll votes, Episode 1 first. Players with no votes yet still appear
    // below the table as "yet to vote".
    picks: {
      Riley: ["Richard", "Matt", "Chloe", "Chloe"],
      Ellen: [],
      Katherine: [],
    },
  },

  21: {
    theme: "diner",
    themeName: "American Diner",
    location: "Hampton Court Palace",
    album: "https://imgur.com/a/taskmaster-series-21-sQsejvk",
    teams: [["Amy", "Joel", "Kumail"], ["Armando", "Joanna"]],
    champion: "Joanna",
    cast: [
      { key: "Amy", full: "Amy Gledhill", color: "#e0424f", img: img("KXhQLQQ"),
        bio: "One half of double act The Delightful Sausage and a Best Newcomer winner at the Edinburgh Comedy Awards." },
      { key: "Armando", full: "Armando Iannucci", color: "#35b58a", img: img("JZSgjrb"),
        bio: "Creator of The Thick of It and Veep, and Oscar-nominated for writing In the Loop." },
      { key: "Joanna", full: "Joanna Page", color: "#f0b429", img: img("IuSCsrt"),
        bio: "Stacey in Gavin & Stacey, and the Series 21 champion." },
      { key: "Joel", full: "Joel Dommett", color: "#3b9be6", img: img("nRfy6Um"),
        bio: "Host of The Masked Singer UK and a former I'm a Celebrity runner-up." },
      { key: "Kumail", full: "Kumail Nanjiani", color: "#9468e8", img: img("u0hZhnG"),
        bio: "Star of Silicon Valley and Oscar-nominated co-writer of The Big Sick." },
    ],
    episodes: [
      { ep: 1, title: "Cube Is Good", date: "2026-04-09" },
      { ep: 2, title: "Leg Up, Johnny!", date: "2026-04-16" },
      { ep: 3, title: "A Creepy Bit of Advice", date: "2026-04-23" },
      { ep: 4, title: "Lou Reed and The Wombles", date: "2026-04-30" },
      { ep: 5, title: "I Corroborate", date: "2026-05-07" },
      { ep: 6, title: "An Even Bigger Spoon", date: "2026-05-14" },
      { ep: 7, title: "Putting Things on Things", date: "2026-05-21" },
      { ep: 8, title: "I Don't Got Any", date: "2026-05-28" },
      { ep: 9, title: "Maybe Someone Else Wrote Veep?", date: "2026-06-04" },
      { ep: 10, title: "Domestic Bumfluff", date: "2026-06-11" },
    ],
    tasks: [

  // Episode 1
  { ep: 1, t: "P", n: "The thing most likely to deter people from your premises", s: [5, 3, 4, 1, 2],
    d: "The thing most likely to deter people from your premises." },
  { ep: 1, t: "F", n: "Protect this egg", s: [0, 0, 0, 0, 0], solo: true,
    d: "Protect this egg. You must have this egg with you unseen for every task and every episode in the studio. You must hand Alex your wholly intact egg within 30 seconds every time the egg timer goes off. If you mention, damage or lose your egg, you are disqualified." },
  { ep: 1, t: "F", n: "Find a worm", s: [4, 2, 3, 5, 1],
    d: "Find a worm." },
  { ep: 1, t: "T", n: "Give Greg five foods correctly", s: [3, 5, 5, 3, 3],
    d: "Give Greg five foods correctly. When the buzzer buzzes, give Greg one food. If you give Greg the wrong food, you must start again. If your buzzer does not buzz, you must stay in this room." },
  { ep: 1, t: "F", n: "Put the most T-shirts on Alex", s: [4, 1, 5, 2, 3],
    d: "Put the most T-shirts on Alex. Alex will only wear T-shirts launched from the T-shirt launcher and onto a target according to the T-shirt launcher rules. You must always launch upwards and each T-shirt can only be launched once. If you catch the golden T-shirt, your T-shirt total will be doubled." },
  { ep: 1, t: "L", n: "Find four oranges", s: [0, 0, 5, 0, 0],
    d: "Find four oranges. If you find an apple, you miss your next go. If you find a lemon, the order reverses. If you find a duck, you must greet the duck by name. If you find an orange, you can look under another can." },
  // Episode 2
  { ep: 2, t: "P", n: "Most unquestionable thing of beauty", s: [5, 4, 5, 3, 1],
    d: "Most unquestionable thing of beauty." },
  { ep: 2, t: "F", n: "Get the bowling ball in the bucket", s: [2, 0, 4, 3, 5],
    d: "Choose how much of Alex's bowling outfit to wear throughout part two. If you choose Alex's bowling overalls, your final time will be reduced by two minutes. If you choose Alex's bowling gloves, your final time will be reduced by three minutes. If you choose Alex's bowling glasses, your final time will be reduced by four minutes. If you choose Alex's bowling shoes, your final time will be reduced by five minutes. If you choose Alex's whole bowling outfit, your final time will be reduced by 20 minutes. Get the bowling ball in the bucket. You must stay onstage at all times. There is a two minute time penalty for every skittle touched and all skittles must be standing when the bowling ball enters the bucket." },
  { ep: 2, t: "F", n: "Do exactly what your reflection does", s: [4, 5, 3, 2, 1],
    d: "Do exactly what your reflection does. You must decide what Alex does, then mirror him." },
  { ep: 2, t: "F", n: "Achieve the most things on this list before the balloon pops", s: [4, 2, 5, 1, 4],
    d: "Achieve the most things on this list before the balloon pops. If you do the special thing, the balloon will stop inflating for 10 seconds. You must not touch the balloon mechanism." },
  { ep: 2, t: "L", n: "Work out what word the piper is piping", s: [5, 4, 2, 4, 2],
    d: "Work out what word the piper is piping. You may have one guess and may only guess if you are the first to raise both hands." },
  // Episode 3
  { ep: 3, t: "P", n: "Most fun thing to drag behind you on a piece of string when you go for a walk", s: [3, 5, 1, 2, 4],
    d: "Most fun thing to drag behind you on a piece of string when you go for a walk." },
  { ep: 3, t: "F", n: "Put on the headphones, obey the instructions, and build the tower", s: [4, 1, 5, 3, 2],
    d: "Put on the headphones, obey the instructions, and build the tower. When you think you have built the correct tower, you must clap three times." },
  { ep: 3, t: "T", n: "Paint the best painting of the painting while hugging", s: [5, 1, 1, 5, 5],
    d: "Paint the best painting of the painting while hugging. One person must always look at the original painting and hug the others with both arms. The others must always look at the new painting. The hugger may only grunt. The painters may ask questions for one minute, then for the rest of the task, they may only say colours, shapes or directions." },
  { ep: 3, t: "F", n: "Get to the top of the staircase", s: [5, 3, 2, 1, 4],
    d: "Get to the top of the staircase. You must take one step at a time. On each step, you must discard a letter and say at least one word. You must not use a word containing a letter you have discarded and you must not repeat any words at any point, otherwise you must start again." },
  { ep: 3, t: "L", n: "Transfer Greg's balls from your bucket to your beaker", s: [5, 3, 3, 1, 4],
    d: "Transfer Greg's balls from your bucket to your beaker. You must wave with one hand at all times and that hand must not touch balls or snooker cues. Also, your snooker cue must balance with one end touching the table at all times, and you can only touch your snooker cue with your non-waving hand. For every one of Alex's balls that ends up in your beaker, three of Greg's balls will be subtracted from your score." },
  // Episode 4
  { ep: 4, t: "P", n: "Best two things that become something even better when combined", s: [1, 4, 3, 5, 2],
    d: "Best two things that become something even better when combined." },
  { ep: 4, t: "F", n: "Make something boring exciting", s: [3, 1, 5, 5, 4],
    d: "Make something boring exciting." },
  { ep: 4, t: "F", n: "Work out what food is under the cloche", s: [4, 0, 5, 0, 3],
    d: "Work out what food is under the cloche. When you have done that, and only when you have done that, you must remove the cloche and eat the food. Alex will always incorrectly answer your previous question and you must not repeat questions." },
  { ep: 4, t: "F", n: "Complete all three tasks", s: [3, 2, 1, 5, 4],
    d: "Complete all three tasks." },
  { ep: 4, t: "L", n: "Be the first to communicate the item to your team", s: [5, 3, 3, 5, 5],
    d: "Be the first to communicate the item to your team. You must not make any noise. You must use your pencil and ball and you must stare at both throughout. You must stay on your spots at all times." },
  // Episode 5
  { ep: 5, t: "P", n: "Most surprising quite big thing to conceal on your person", s: [2, 5, 1, 4, 3],
    d: "Most surprising quite big thing to conceal on your person." },
  { ep: 5, t: "F", n: "Write down a prediction for an unlikely situation to occur", s: [3, 5, 3, 3, 4],
    d: "Write down a prediction for an unlikely situation to occur in exactly 15 minutes' time, then make that unlikely situation occur." },
  { ep: 5, t: "T", n: "Win sardines", s: [3, 5, 5, 3, 3],
    d: "Win sardines. Split up and search for Alex. You must not be within sight of each other while searching. Also, you must only whisper and when you find Alex, you must stay with him and remain silent. Team: two of you must hold hands at all times." },
  { ep: 5, t: "F", n: "Get a ball in the glass", s: [2, 5, 4, 3, 1],
    d: "Get a ball in the glass. You may not move the pipe or the glass. The ball must travel through the pipe and you must not do anything to influence the ball's movement after you release the ball." },
  { ep: 5, t: "L", n: "Swing your ring onto your thing to win a ring", s: [1, 4, 3, 3, 5],
    d: "Swing your ring onto your thing to win a ring. If you win a ring, you swing again." },
  // Episode 6
  { ep: 6, t: "P", n: "Most embarrassing possession", s: [2, 2, 5, 4, 3],
    d: "Most embarrassing possession." },
  { ep: 6, t: "F", n: "Be brave", s: [3, 4, 2, 4, 5],
    d: "Be brave." },
  { ep: 6, t: "F", n: "Win coconkers", s: [2, 3, 4, 1, 5],
    d: "Win coconkers. Coconkers is conkers with coconuts. You can prepare your coconker however you like, as long as it still looks like a coconker." },
  { ep: 6, t: "F", n: "Appear in the most photos holding a different thing in your mouth", s: [5, 1, 3, 4, 2],
    d: "Appear in the most photos holding a different thing in your mouth, each thing bigger than the last thing. Only one of your things may be in the lab at any one time. The camera will take a picture once every 10 seconds for 10 minutes." },
  { ep: 6, t: "L", n: "Land beanbags on your opponents' faces", s: [4, 1, 2, 3, 5],
    d: "Land beanbags on your opponents' faces. If your face is struck three times, you are eliminated. You may only throw one beanbag at a time and you must throw from your spot. If you strike the Taskmaster's face, the Taskmaster will launch his own double-strength beanbag." },
  // Episode 7
  { ep: 7, t: "P", n: "Best bumpy thing", s: [2, 3, 1, 4, 5],
    d: "Best bumpy thing." },
  { ep: 7, t: "F", n: "Turn on the telly", s: [2, 4, 3, 1, 5],
    d: "Turn on the telly. You may not touch the telly. You must now also find and eat a doughnut before you finish the task." },
  { ep: 7, t: "T", n: "Completely revoice this footage to create a dramatic short film", s: [2, 5, 5, 2, 2],
    d: "Completely revoice this footage to create a dramatic short film. You must not revoice yourself." },
  { ep: 7, t: "F", n: "Make the most socks stand up", s: [3, 5, 2, 1, 4],
    d: "Make the most socks stand up." },
  { ep: 7, t: "L", n: "Snort, raspberry or whistle in the order the Taskmaster desires", s: [1, 5, 4, 2, 3],
    d: "Snort, raspberry or whistle in the order the Taskmaster desires. The Taskmaster will give you a number sequence and you must reply immediately with the corresponding noises. One equals snort, two equals raspberry, three equals whistle. If you make a mistake, you are out." },
  // Episode 8
  { ep: 8, t: "P", n: "An ordinary household object with the most personality", s: [3, 3, 4, 2, 5],
    d: "An ordinary household object with the most personality." },
  { ep: 8, t: "F", n: "Censor yourself unnecessarily", s: [5, 4, 4, 4, 4],
    d: "Censor yourself unnecessarily." },
  { ep: 8, t: "F", n: "Take the most photos featuring at least 50% of the Taskmaster's Assistant", s: [4, 4, 2, 1, 5],
    d: "Take the most photos featuring at least 50% of the Taskmaster's Assistant. The Taskmaster's Assistant must stay within the arena and will run when you clap. You must wear your blindfold correctly at all times and must not run. You have a maximum of 24 pictures." },
  { ep: 8, t: "F", n: "Put nine nuts and/or nails in the nappy", s: [5, 2, 3, 4, 1],
    d: "Do not look away from this task. Put nine nuts and/or nails in the nappy. Every time you look away, one minute will be added to your time." },
  { ep: 8, t: "L", n: "Tell your teammate when to stop with their mop", s: [2, 5, 5, 2, 2],
    d: "Wearing your mask correctly at all times, tell your teammate when to stop with their mop. The mop bearer must slowly walk at a constant pace and softly squeak at a constant volume." },
  // Episode 9
  { ep: 9, t: "P", n: "The thing you would most enjoy winching up from a well in a bucket", s: [5, 4, 3, 2, 1],
    d: "The thing you would most enjoy winching up from a well in a bucket." },
  { ep: 9, t: "F", n: "Work out what powers the bulb in the lab", s: [2, 0, 5, 4, 3],
    d: "Work out what powers the bulb in the lab. You may only give one answer and you may only enter the lab once." },
  { ep: 9, t: "F", n: "Leave the most pink balls on the other side of the court", s: [1, 5, 3, 2, 4],
    d: "Leave the most pink balls on the other side of the court at the end of the task. You may only touch balls with racquets. You will lose one pink ball for every blue ball left on your side of the court at the end of the task. Alex must freeze for 30 seconds every time you strike the gong with a ball." },
  { ep: 9, t: "F", n: "Write down a forfeit for a contestant who does not complete the flip-flop task", s: [4, 3, 1, 5, 2],
    d: "Write down a forfeit for a contestant who does not complete the flip-flop task. Catch a flip-flop flung from the flip-flop flinger with one foot. You may not use your hands. You have flive attempts. If you fail, you must do a flip-flop forfeit." },
  { ep: 9, t: "L", n: "Put the correct sock on an appendage and poke it out of the correct hole first", s: [1, 5, 2, 3, 4],
    d: "Put the correct sock on an appendage and poke it out of the correct hole first. The fastest each time goes through to the next round and one person is eliminated each round." },
  // Episode 10
  { ep: 10, t: "P", n: "The object that is most likely to make you say \"Oh, yeah, that is quality\" when you see it", s: [1, 5, 4, 3, 2],
    d: "The object that is most likely to make you say \"Oh, yeah, that is quality\" when you see it." },
  { ep: 10, t: "F", n: "Fill this egg cup with lint", s: [1, 4, 3, 5, 2],
    d: "Fill this egg cup with lint. The egg cup must stay in the lab. Also, you must stop this clock at exactly 10 seconds at some point in the second half of your attempt, otherwise you are disqualified." },
  { ep: 10, t: "F", n: "Have the most exhilarating near-miss with this paint balloon", s: [2, 4, 3, 5, 2],
    d: "Have the most exhilarating near-miss with this paint balloon." },
  { ep: 10, t: "T", n: "Choreograph and carry out the greatest pillow fight of all time", s: [5, 5, 5, 5, 5],
    d: "Choreograph and carry out the greatest pillow fight of all time." },
  { ep: 10, t: "L", n: "Chuck your duck in your buck", s: [3, 2, 1, 5, 4],
    d: "Chuck your duck in your buck. You must sit on your chair at all times and you must not touch the ground or anything other than your chair or duck with any part of your body." },
    ],
    picks: {},
  },
};
